package com.jets.chatproject.server.module.dal.hibernate.entity;
// Generated Mar 10, 2019 4:24:14 PM by Hibernate Tools 4.3.1



/**
 * GroupMembers generated by hbm2java
 */
public class GroupMembers  implements java.io.Serializable {


     private GroupMembersId id;
     private GroupMessages groupMessages;
     private Groups groups;
     private Users users;

    public GroupMembers() {
    }

	
    public GroupMembers(GroupMembersId id, Groups groups, Users users) {
        this.id = id;
        this.groups = groups;
        this.users = users;
    }
    public GroupMembers(GroupMembersId id, GroupMessages groupMessages, Groups groups, Users users) {
       this.id = id;
       this.groupMessages = groupMessages;
       this.groups = groups;
       this.users = users;
    }
   
    public GroupMembersId getId() {
        return this.id;
    }
    
    public void setId(GroupMembersId id) {
        this.id = id;
    }
    public GroupMessages getGroupMessages() {
        return this.groupMessages;
    }
    
    public void setGroupMessages(GroupMessages groupMessages) {
        this.groupMessages = groupMessages;
    }
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


