package com.jets.chatproject.server.module.dal.hibernate.entity;
// Generated Mar 10, 2019 4:24:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private Integer groupId;
     private Pictures pictures;
     private Users users;
     private String displayName;
     private Set groupMessageses = new HashSet(0);
     private Set groupMemberses = new HashSet(0);

    public Groups() {
    }

	
    public Groups(Users users, String displayName) {
        this.users = users;
        this.displayName = displayName;
    }
    public Groups(Pictures pictures, Users users, String displayName, Set groupMessageses, Set groupMemberses) {
       this.pictures = pictures;
       this.users = users;
       this.displayName = displayName;
       this.groupMessageses = groupMessageses;
       this.groupMemberses = groupMemberses;
    }
   
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
    public Pictures getPictures() {
        return this.pictures;
    }
    
    public void setPictures(Pictures pictures) {
        this.pictures = pictures;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public Set getGroupMessageses() {
        return this.groupMessageses;
    }
    
    public void setGroupMessageses(Set groupMessageses) {
        this.groupMessageses = groupMessageses;
    }
    public Set getGroupMemberses() {
        return this.groupMemberses;
    }
    
    public void setGroupMemberses(Set groupMemberses) {
        this.groupMemberses = groupMemberses;
    }




}


