package com.jets.chatproject.server.module.dal.hibernate.entity;
// Generated Mar 10, 2019 4:24:14 PM by Hibernate Tools 4.3.1



/**
 * GroupMembersId generated by hbm2java
 */
public class GroupMembersId  implements java.io.Serializable {


     private int groubId;
     private int userId;

    public GroupMembersId() {
    }

    public GroupMembersId(int groubId, int userId) {
       this.groubId = groubId;
       this.userId = userId;
    }
   
    public int getGroubId() {
        return this.groubId;
    }
    
    public void setGroubId(int groubId) {
        this.groubId = groubId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GroupMembersId) ) return false;
		 GroupMembersId castOther = ( GroupMembersId ) other; 
         
		 return (this.getGroubId()==castOther.getGroubId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGroubId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


