package com.jets.chatproject.server.module.dal.hibernate.entity;
// Generated Mar 10, 2019 4:24:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Requests generated by hbm2java
 */
public class Requests  implements java.io.Serializable {


     private RequestsId id;
     private Users usersByReceiverId;
     private Users usersBySenderId;
     private Date time;

    public Requests() {
    }

    public Requests(RequestsId id, Users usersByReceiverId, Users usersBySenderId, Date time) {
       this.id = id;
       this.usersByReceiverId = usersByReceiverId;
       this.usersBySenderId = usersBySenderId;
       this.time = time;
    }
   
    public RequestsId getId() {
        return this.id;
    }
    
    public void setId(RequestsId id) {
        this.id = id;
    }
    public Users getUsersByReceiverId() {
        return this.usersByReceiverId;
    }
    
    public void setUsersByReceiverId(Users usersByReceiverId) {
        this.usersByReceiverId = usersByReceiverId;
    }
    public Users getUsersBySenderId() {
        return this.usersBySenderId;
    }
    
    public void setUsersBySenderId(Users usersBySenderId) {
        this.usersBySenderId = usersBySenderId;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


