package com.jets.chatproject.server.module.dal.hibernate.entity;
// Generated Mar 10, 2019 4:24:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private Pictures pictures;
     private String phoneNumber;
     private String displayName;
     private String email;
     private String password;
     private String state;
     private String gender;
     private String country;
     private Date dateOfBirth;
     private String bio;
     private Byte systemRegistration;
     private Set friendshipsesForUserId = new HashSet(0);
     private Set friendshipsesForFriendId = new HashSet(0);
     private Set groupses = new HashSet(0);
     private Set groupMessageses = new HashSet(0);
     private Set requestsesForReceiverId = new HashSet(0);
     private Set requestsesForSenderId = new HashSet(0);
     private Set directMessagesesForReceiverId = new HashSet(0);
     private Set directMessagesesForSenderId = new HashSet(0);
     private Set groupMemberses = new HashSet(0);

    public Users() {
    }

	
    public Users(String phoneNumber, String displayName, String email, String password, String gender, String country, Date dateOfBirth, String bio) {
        this.phoneNumber = phoneNumber;
        this.displayName = displayName;
        this.email = email;
        this.password = password;
        this.gender = gender;
        this.country = country;
        this.dateOfBirth = dateOfBirth;
        this.bio = bio;
    }
    public Users(Pictures pictures, String phoneNumber, String displayName, String email, String password, String state, String gender, String country, Date dateOfBirth, String bio, Byte systemRegistration, Set friendshipsesForUserId, Set friendshipsesForFriendId, Set groupses, Set groupMessageses, Set requestsesForReceiverId, Set requestsesForSenderId, Set directMessagesesForReceiverId, Set directMessagesesForSenderId, Set groupMemberses) {
       this.pictures = pictures;
       this.phoneNumber = phoneNumber;
       this.displayName = displayName;
       this.email = email;
       this.password = password;
       this.state = state;
       this.gender = gender;
       this.country = country;
       this.dateOfBirth = dateOfBirth;
       this.bio = bio;
       this.systemRegistration = systemRegistration;
       this.friendshipsesForUserId = friendshipsesForUserId;
       this.friendshipsesForFriendId = friendshipsesForFriendId;
       this.groupses = groupses;
       this.groupMessageses = groupMessageses;
       this.requestsesForReceiverId = requestsesForReceiverId;
       this.requestsesForSenderId = requestsesForSenderId;
       this.directMessagesesForReceiverId = directMessagesesForReceiverId;
       this.directMessagesesForSenderId = directMessagesesForSenderId;
       this.groupMemberses = groupMemberses;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Pictures getPictures() {
        return this.pictures;
    }
    
    public void setPictures(Pictures pictures) {
        this.pictures = pictures;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getBio() {
        return this.bio;
    }
    
    public void setBio(String bio) {
        this.bio = bio;
    }
    public Byte getSystemRegistration() {
        return this.systemRegistration;
    }
    
    public void setSystemRegistration(Byte systemRegistration) {
        this.systemRegistration = systemRegistration;
    }
    public Set getFriendshipsesForUserId() {
        return this.friendshipsesForUserId;
    }
    
    public void setFriendshipsesForUserId(Set friendshipsesForUserId) {
        this.friendshipsesForUserId = friendshipsesForUserId;
    }
    public Set getFriendshipsesForFriendId() {
        return this.friendshipsesForFriendId;
    }
    
    public void setFriendshipsesForFriendId(Set friendshipsesForFriendId) {
        this.friendshipsesForFriendId = friendshipsesForFriendId;
    }
    public Set getGroupses() {
        return this.groupses;
    }
    
    public void setGroupses(Set groupses) {
        this.groupses = groupses;
    }
    public Set getGroupMessageses() {
        return this.groupMessageses;
    }
    
    public void setGroupMessageses(Set groupMessageses) {
        this.groupMessageses = groupMessageses;
    }
    public Set getRequestsesForReceiverId() {
        return this.requestsesForReceiverId;
    }
    
    public void setRequestsesForReceiverId(Set requestsesForReceiverId) {
        this.requestsesForReceiverId = requestsesForReceiverId;
    }
    public Set getRequestsesForSenderId() {
        return this.requestsesForSenderId;
    }
    
    public void setRequestsesForSenderId(Set requestsesForSenderId) {
        this.requestsesForSenderId = requestsesForSenderId;
    }
    public Set getDirectMessagesesForReceiverId() {
        return this.directMessagesesForReceiverId;
    }
    
    public void setDirectMessagesesForReceiverId(Set directMessagesesForReceiverId) {
        this.directMessagesesForReceiverId = directMessagesesForReceiverId;
    }
    public Set getDirectMessagesesForSenderId() {
        return this.directMessagesesForSenderId;
    }
    
    public void setDirectMessagesesForSenderId(Set directMessagesesForSenderId) {
        this.directMessagesesForSenderId = directMessagesesForSenderId;
    }
    public Set getGroupMemberses() {
        return this.groupMemberses;
    }
    
    public void setGroupMemberses(Set groupMemberses) {
        this.groupMemberses = groupMemberses;
    }




}


